package main

import "fmt"

func getErr(int1, int2 int) error {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	_ = int1 / int2
	return nil
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	_ = getErr(1, 0)
	fmt.Println("Hello, playground")

}
